services:
  snapper:
    build: .
    container_name: webcam-snapper
    environment:
      STREAM_URL: ${STREAM_URL}
      OUTDIR: /data/images
      INTERVAL: ${INTERVAL:-20}
      QUALITY: ${QUALITY:-2}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_TERM_MSG: ${WEBHOOK_TERM_MSG}
      WEBHOOK_WARN_MSG: ${WEBHOOK_WARN_MSG}
      WEBHOOK_RECOV_MSG: ${WEBHOOK_RECOV_MSG}
      RESTART_WARN_THRESHOLD: ${RESTART_WARN_THRESHOLD:-10}
      RESTART_LIMIT: ${RESTART_LIMIT:-200}
      MAX_RESTART_DELAY: ${MAX_RESTART_DELAY:-300}
      PROC_HEALTHY_START_MULTIPLIER: ${PROC_HEALTHY_START_MULTIPLIER:-4}
      PROC_UNRESPONSIVE_MULTIPLIER: ${PROC_UNRESPONSIVE_MULTIPLIER:-6}
    volumes:
      - ./images:/data/images

